version: '3.8'

services:
  frontend:
    build: ./frontend/student-predictor
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env