name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - tensorflow
  - fastapi
  - uvicorn
  - motor
  - pymongo
  - pandas
  - scikit-learn
  - python-dotenv
  - joblib
  - pip:
      - certifi
